"""Deterministic recurring-payment occurrence math (spec §24, §25, §26).

Each recurring payment stores only its *next* due date. Expected future
occurrences within a window are generated by stepping next_payment_date
forward by the payment's frequency interval — no ML, no guessing. A payment
whose next_payment_date is already inside the window counts as-is; one
before the window is stepped forward until it lands inside (or past) it.
"""

import calendar
import datetime
from decimal import Decimal

from .models import RecurringPayment


def _add_months(date: datetime.date, months: int) -> datetime.date:
    month_index = date.month - 1 + months
    year = date.year + month_index // 12
    month = month_index % 12 + 1
    day = min(date.day, calendar.monthrange(year, month)[1])
    return date.replace(year=year, month=month, day=day)


_FREQUENCY_STEP = {
    RecurringPayment.Frequency.WEEKLY: lambda d: d + datetime.timedelta(days=7),
    RecurringPayment.Frequency.MONTHLY: lambda d: _add_months(d, 1),
    RecurringPayment.Frequency.QUARTERLY: lambda d: _add_months(d, 3),
    RecurringPayment.Frequency.YEARLY: lambda d: _add_months(d, 12),
}


def get_occurrences_in_range(payment, start: datetime.date, end: datetime.date) -> list[datetime.date]:
    """Due dates for one recurring payment within [start, end], inclusive."""
    if not payment.is_active:
        return []

    step = _FREQUENCY_STEP[payment.frequency]
    current = payment.next_payment_date
    while current < start:
        current = step(current)

    occurrences = []
    while current <= end:
        occurrences.append(current)
        current = step(current)
    return occurrences


def get_expected_totals_by_currency(
    user,
    start: datetime.date,
    end: datetime.date,
    exclude_expense_category_ids=frozenset(),
) -> dict:
    """Expected recurring income/expense within [start, end], grouped by
    currency. exclude_expense_category_ids skips expense payments whose
    category is passed in — used by available-to-spend to avoid double
    counting a recurring expense that an active budget already reserves for
    (spec §25)."""

    payments = RecurringPayment.objects.filter(user=user, is_active=True)
    totals = {}
    for payment in payments:
        if payment.type == RecurringPayment.Type.EXPENSE and payment.category_id in exclude_expense_category_ids:
            continue

        occurrences = get_occurrences_in_range(payment, start, end)
        if not occurrences:
            continue

        entry = totals.setdefault(payment.currency, {"income": Decimal("0.00"), "expense": Decimal("0.00")})
        amount = Decimal(str(payment.amount)) * len(occurrences)
        entry[payment.type] += amount

    return totals
